### ISSUE TITLE
Removing Matches is not intuitive

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/NetDiff#18]

**Comment by NullVoxPopuli** [comment]
how so?

**Comment by etkirsch** [comment]
How is it done? Do you call it on the result object? We were having trouble figuring it out this afternoon. In all of the instances we had a result object of type BaseDiff, which doesn't have the WithoutMatching method.

We should come up with something for this, because I'm having trouble figuring it out.

**Comment by NullVoxPopuli** [comment]
I thought it was a constructor parameter on the calculator? https://github.com/etkirsch/NetDiff/blob/master/NetDiff/DiffCalculator.cs#L22

Did that not work?

**Comment by etkirsch** [comment]
Huh. That's not in the package for some reason.

**Comment by NullVoxPopuli** [comment]
Did you do the copy to lib folderr thing?

**Comment by etkirsch** [comment]
Of course

**Comment by NullVoxPopuli** [comment]
Yeah, the steps are
 
- Build
- Copy bin DLLs to lib.
- Nuget pack
- Nuget push

**Comment by etkirsch** [comment]
Yeah I did that. Turns out Powershell dropped the ball last time. It "pushed" but I don't think it really did anything. I had to kill the process. Trying it again fixed it.

**Comment by etkirsch** [comment]
not sure why I closed this

**Comment by NullVoxPopuli** [comment]
Classic powershell

**Comment by NullVoxPopuli** [comment]
looks like the wrong entry point was used. It is now documented in the readme.

We should probably discourage use of any DiffObjects / DiffList methods in the calculator.
