### ISSUE TITLE
Rename Diffed models

### ISSUE THREAD

**Issue by NullVoxPopuli** [etkirsch/NetDiff#8]
The naming convention is kinda wonky.

For example:

- diffed field 
- diffed item
- diffed object

these make sense as they are all the state of a thing.

where things get weird, is when we need to track an ignored object.

- diffed ignored object

that's kinda awkward

Maybe we could change the naming convention of these to:

- FieldDiff
- IgnoredDiff
- ItemDiff (superclass)
- ObjectDiff

thoughts?

**Comment by etkirsch** [comment]
Approving this. Additionally we'll go from DiffedItem to BaseDiff
